'use client'

import { Analytics } from '@vercel/analytics/next'
import { Toaster } from "@/components/ui/sonner";
import Header from "./_components/Header";
import "./globals.css";
import { usePathname } from "next/navigation";
import { UpdateCartContext } from "./_context/UpdateCartContext";
import { useState } from "react";
import { Orbitron } from "next/font/google"

const orbitron = Orbitron({ subsets: ['latin']})

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const params = usePathname()
  const showHeader = params == '/sign-in'|| params == '/create-account' ? false : true

  const [updateCart, setUpdateCart] = useState(false)

  return (
    <html lang="nl">
      <body
        className={orbitron.className}
      >
        <UpdateCartContext.Provider value={{updateCart, setUpdateCart}}>
        {showHeader&&<Header />}
        {children}
        <Analytics />
        <Toaster />
        </UpdateCartContext.Provider>
      </body>
    </html>
  );
}
